#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/pushserver/pushserver"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/pushserver/pushserver &
	fi
	echo "pushserver is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/pushserver/pushserver"` 2>/dev/null
	echo "pushserver exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}
