#!/bin/sh /etc/rc.common
#
# Copyright (C) 2020 Jerryk
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

USE_PROCD=1
START=25

NAME=jd-signdog
CRON_FILE=/etc/crontabs/root


del_cron() {
	sed -i '/jd-signdog/d' $CRON_FILE
	/etc/init.d/cron restart
}

start_service(){
	/usr/share/jd-signdog/newapp.sh -s
}

stop_service() {
    del_cron
}

service_triggers() {
	procd_add_reload_trigger "jd-signdog"
}